// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// getdC
Rcpp::List getdC(const mat& X, const colvec& v, const double& s2, const double& tau2, const colvec& y);
RcppExport SEXP _RcppTBASS_getdC(SEXP XSEXP, SEXP vSEXP, SEXP s2SEXP, SEXP tau2SEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const colvec& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const double& >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< const double& >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< const colvec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(getdC(X, v, s2, tau2, y));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_hello_world
arma::mat rcpparma_hello_world();
RcppExport SEXP _RcppTBASS_rcpparma_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpparma_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_outerproduct
arma::mat rcpparma_outerproduct(const arma::colvec& x);
RcppExport SEXP _RcppTBASS_rcpparma_outerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_outerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_innerproduct
double rcpparma_innerproduct(const arma::colvec& x);
RcppExport SEXP _RcppTBASS_rcpparma_innerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_innerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_bothproducts
Rcpp::List rcpparma_bothproducts(const arma::colvec& x);
RcppExport SEXP _RcppTBASS_rcpparma_bothproducts(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_bothproducts(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppTBASS_getdC", (DL_FUNC) &_RcppTBASS_getdC, 5},
    {"_RcppTBASS_rcpparma_hello_world", (DL_FUNC) &_RcppTBASS_rcpparma_hello_world, 0},
    {"_RcppTBASS_rcpparma_outerproduct", (DL_FUNC) &_RcppTBASS_rcpparma_outerproduct, 1},
    {"_RcppTBASS_rcpparma_innerproduct", (DL_FUNC) &_RcppTBASS_rcpparma_innerproduct, 1},
    {"_RcppTBASS_rcpparma_bothproducts", (DL_FUNC) &_RcppTBASS_rcpparma_bothproducts, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppTBASS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
