# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getdC <- function(X, v, s2, tau2, y) {
    .Call('_TBASS_getdC', PACKAGE = 'TBASS', X, v, s2, tau2, y)
}

